name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      
    runs-on: ${{ matrix.os }}
    env:
      app_name: app_${{ matrix.os }}_${{ github.run_number }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -o ${{ env.app_name }}

    - name: Test
      run: go test -v ./...
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact-matrix
        path: ${{ env.app_name }}
        retention-days: 5
