name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      
    runs-on: ${{ matrix.os }}
    env:
      app_name: app_${{ matrix.os }}_${{ github.run_number }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -o ${{ env.app_name }}

    - name: Test
      run: go test -v ./...
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: artifacts_folder
        path: ${{ env.app_name }}
        retention-days: 5

  telegram:
    needs: build_matrix

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with: 
          name: artifacts_folder
          path: artifacts

      - name: Send to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Github Artifacts
          document: artifacts/**